### ISSUE TITLE
Bug when displaying the user name in the poll table

### ISSUE THREAD

**Issue by vmassol** [xwikisas/application-xpoll#32]
<img width="1483" alt="team_activity___cooking_workshop__xpoll_team_activity____cooking_workshop_webhome__-_xwiki" src="https://user-images.githubusercontent.com/628267/53245077-07d2ac00-36ad-11e9-8402-083e7d5e0f4f.png">

**Comment by vmassol** [comment]
Maybe `$xwiki.getUserName($user)` is not working when in a subwiki or in domain-based or...

**Comment by vmassol** [comment]
The problem is that `wiki=true` is used in `{{html clean='false' wiki='true'}}`

**Comment by vmassol** [comment]
Idea: use a better displayer for the user. We have displayers showing both avatars and name.

**Comment by lucaa** [comment]
Quick solution: getUserName() takes a second parameter controlling whether html should be generated or not. 
Long solution: proper sheet that avoids using {{html wiki=true }} (which is generally a bad idea and the proof of that is this issue) and, as Vincent said, also improves the user display.

**Comment by lucaa** [comment]
On a 1.10.4 version of the poll application, on a subwiki of a farm with global users , this issue is not fixed as it's replaced with a new issue: broken avatar macro and broken link to the user page:
![image](https://user-images.githubusercontent.com/657716/55171616-faf81b00-5178-11e9-8f4a-0cf390f54371.png)

I am reopening this issue also it's arguable whether the bug is a new one or the same as this one (it's obviously not the same, but the user display is still not ok).
