### ISSUE TITLE
Add support for a Condorcet method poll 

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-xpoll#76]
Currently the poll application supports simple voting for options and simple majority vote counting method for announcing the winner.

There are alternative election methods, whose purpose is to maximize global satisfaction with the result by allowing electors to also express their "second option", and third option and so on https://en.wikipedia.org/wiki/Condorcet_method  .

It would be interesting to support this election method in the XPoll application, I see it as a poll type option along with "single choice" and "multiple choice" that are available today.

**Comment by trrenty** [comment]
Hello there

After studying the way things work with this Application, I came up with the following way of handling this issue.

For this feature we would need to keep track of the checkbox selection order. We can track this by assigning a value to each input before sending the form. When the form is handled by the [XPollService](https://github.com/xwikisas/application-xpoll/blob/master/application-xpoll-ui/src/main/resources/XPoll/XPollService.xml), a PollVote object will be created/modified with the votes in the order or the selection. This won't affect the other ways of determining the winner of the poll.

Now that we have the preferences of each user in order, we can determine the winner using the Condorcet Method.

For the ordering part I was thinking of using a code similar to [this](https://stackoverflow.com/questions/3830961/javascript-checkbox-selection-order#answer-3831175) to save the order into an array and, before saving, assigning each checkbox it's corresponding index. 

Afterwards, I should make some modifications inside the XPollService, where the request is handled. Once to assign the user the votes in the proper order ([here](https://github.com/xwikisas/application-xpoll/blob/master/application-xpoll-ui/src/main/resources/XPoll/XPollService.xml#L50-L63)) and once to determine the winner with the new method. I was thinking of handling the latter with a simple if.
```
if (pollType == condorcet) {
  // determine winner using condorcet method
} else {
  // determine winner in the traditional manner
}
```
Wdyt?

**Comment by mflorea** [comment]
Hi Teodor, it's not clear to me how the user knows the order of the selected options just by looking at the check boxes. The user may know the order when they vote, but if they come back after one week they might forgot. The order needs to be clearly visible. Don't you agree?

**Comment by trrenty** [comment]
For the moment I was thinking that a label with a number next to the checkboxes should do the trick. But I also thought that since we have the order of their votes, we can forge the UI in whatever way we want.

**Comment by mflorea** [comment]
The UIX you propose is a bit cumbersome when there are multiple choices. Let's say you have 6 choices. If you know the order you want to apply then you need 6 clicks. That's fine. The problem is if you change your mind. Say for instance if you want to change your number 1 pick. You'd have to:

* either unselect everything and then redo the selection with the new order (12 clicks)
* or use some "Clear all" option and then redo the selection with the new order (still 6 clicks)

I think there are better UIX solutions that we could implement. One option is to use drag & drop to change the order. Another one is to use a drop down with the order (1-6) instead of a check box. My point is that we need to see what is the best way for the user to vote using the Condorcet method. I know that what you proposed integrates well with the current display of the poll, but I feel it's not the best option for the user (it may be the best option for the developer :) ). Would be good to check how other voting tools behave when the Condorcet method is used (i.e. check what others do). In the end we will probably make a compromise, but at least we would know that we didn't implement A or B because it was too costly or something else.

> For the moment I was thinking that a label with a number next to the checkboxes should do the trick.

This could help visualize the order, but it doesn't fix the "problem" of editing your vote when you change your mind.

**Comment by trrenty** [comment]
I took a look around. I could find three main ways in which people handle ranked options.

I created some images to visualize how each of them would look inside xwiki.

The first one would be Google Form's way of handling it - a matrix in which the lines represent the hierarchy and the columns representing the proposals.

![240993984_1515999025423084_3612680250271977919_n](https://user-images.githubusercontent.com/45433221/131803961-16d5dec8-3a8e-4e01-af93-e212ed2a06e8.jpg)

The second option for the UI would be something [Survey Monkey does](https://help.surveymonkey.com/articles/en_US/kb/How-do-I-create-a-Ranking-type-question) and the one you mentioned - drag and dropping.

![241054415_964871314294477_451845477465020275_n](https://user-images.githubusercontent.com/45433221/131804352-4c9f1a34-b2d1-4c14-abac-d39b7eaae330.jpg)

And the third one, one you also mentioned, is having multiple selects instead of checkboxes.
![240955230_2991923754397054_8656751123229507369_n](https://user-images.githubusercontent.com/45433221/131804645-75254347-6f6b-4425-9d51-97b0002ed9a7.jpg)

As you can see in the images, for viewing the votes of the other users, I used the method mentioned in my previous comment - number beside each checkbox, but we could also use different ways of displaying them, such as the drag and dropping boxes.

**Comment by mflorea** [comment]
> The matrix method is pretty bad - imo.

I agree.

> I personally think the drag and dropping method looks the best but I'm not sure about its complexity, the select method also looks pretty good and it's simpler. And besides the looks, they should also be really user friendly, compared to the checkboxes.

Yes. The drag & drop solution will be a bit more complex to implement so I'd start with the drop down solution. Thus I think we should go with:

* view: show the the options that have been checked, followed by a label indicating the order of preference as you suggested (the numbers need to be styled in a special way so that they look like a label; Bootstrap's ``label`` or ``badge`` could work).
* edit: show a drop down (to select the order) instead of a checkbox; of course, the drop down should allow the user to not select the value (as if that option was not selected if a check box were used)

@lucaa WDYT? Does this sound good enough for a first version?

**Comment by lucaa** [comment]
> @lucaa WDYT? Does this sound good enough for a first version?

yep, sounds good (I only got to read it now). IIUC this is what was implemented for closing this issue, right?
